### ISSUE TITLE
Out of preview?

### ISSUE THREAD

**Issue by espenrl** [IdentityModel/IdentityModel.AspNetCore.AccessTokenValidation#1]
Hi and thanks for a greate little library. When will the final 1.0.0 release be?

**Comment by leastprivilege** [comment]
I am actually not sure if this is worth releasing - this is more like a gist than a nuget package...

**Comment by espenrl** [comment]
Ah, ok. It could be an idea to mentioned that in README.md

I will copy the code to my project then. Thanks for the gist :)

**Comment by leastprivilege** [comment]
Well - if GitHub would only support organization gists....
